# Generated by Django 6.0.1 on 2026-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(default='919999999999', max_length=15)),
                ('property_type', models.CharField(choices=[('FLAT', 'Flat/Apartment'), ('HOUSE', 'Independent House'), ('ROOM', 'Single Room'), ('COMMERCIAL', 'Commercial Space')], max_length=20)),
                ('listing_type', models.CharField(choices=[('RENT', 'For Rent'), ('SELL', 'For Sale')], max_length=20)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('is_furnished', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_gallery/')),
            ],
        ),
    ]
