# Generated by Django 6.0.1 on 2026-01-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_buyer_property_is_sold_alter_property_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
