# Generated by Django 6.0.1 on 2026-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(default='919999999999', max_length=15),
        ),
    ]
