# Generated by Django 6.0.1 on 2026-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_document',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('COMPANY', 'Movers & Packers Company')], default='BUYER', max_length=10),
        ),
    ]
